Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-08, with the labels that each got.

#112 Support preview csv
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/CsvPreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
Labels: approved, lgtm, size/M

#113 Support preview image
  src/components/atoms/FileMenuItem.tsx
  src/components/molecules/FilePreviewer/ImagePreviewer.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
Labels: approved, size/M

#116 Support preview markdown
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/MarkDownPreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
Labels: approved, size/L

#115 Support preview source code
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/SourceCodePreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
Labels: approved, size/L

#118 Fix README
  README.md
Labels: approved

#117 Show formatted record info
  package-lock.json
  package.json
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordInfoTable.tsx
Labels: approved, size/L

#119 Add initial config for easy starting to use database
  src/utils/index.ts
Labels: approved, lgtm, size/S

#121 Fix import path
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/FilePreviewer/AudioPreviewer.tsx
  src/components/molecules/Sample.tsx
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/InputConfigAddModal.tsx
Labels: approved, lgtm, size/S

#126 Add button for viewing neighbor file in file previewing dialog
  src/components/organisms/FileList.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/utils/fetchClients.tsx
  src/utils/index.ts
Labels: approved, size/L, lgtm

#128 Apply delete mode for confirm modal on deleting
  package-lock.json
  package.json
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/RecordList.tsx
Labels: size/S, approved, lgtm

#129 Configure to automate sorting import and deleting unused import
  .eslintrc.js
  package-lock.json
  package.json
Labels: approved, size/L

#124 Rewrite Sample component by new coding style
  src/components/molecules/Sample.tsx
Labels: size/M, approved

#120 Move delete database button to deeper place
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseDeleteModal.stories.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordList.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
  src/utils/index.ts
Labels: approved, size/XL

#131 Sort import path
  src/components/atoms/AddListItemButton.tsx
  src/components/atoms/FileMenuItem.stories.tsx
  src/components/atoms/FileMenuItem.tsx
  src/components/atoms/RenderToggleByAction.tsx
  src/components/molecules/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/molecules/Breadcrumbs/index.tsx
  src/components/molecules/DatabaseMenu.stories.tsx
  src/components/molecules/DatabaseMenuButton.tsx
  src/components/molecules/FileMenu.stories.tsx
  src/components/molecules/FileMenu.tsx
  src/components/molecules/FilePreviewer/AudioPreviewer.tsx
  src/components/molecules/FilePreviewer/CsvPreviewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/SourceCodePreviewer.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/molecules/OptionSharingSelectsItem.tsx
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseConfigModal.tsx
  src/components/organisms/DatabaseListItem.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/FileListItem.stories.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/components/organisms/InputConfigAddModal.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/MetadataEditModal.stories.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordAddButton.tsx
  src/components/pages/RecordsPage.tsx
  src/pages/[[...app]].tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/test-utils.tsx
  src/utils/fetchClients.tsx
Labels: approved, size/L

#132 Bump Material-ui from alpha.30 to beta.4
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/atoms/AddListItemButton.tsx
  src/components/atoms/ElemCenteringFlexDiv.tsx
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/DatabaseMenuButton.stories.tsx
  src/components/molecules/FilePreviewer/ImagePreviewer.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/molecules/OptionSharingSelectsItem.tsx
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseDeleteModal.stories.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordInfoTable.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/test-utils.tsx
Labels: approved, size/XL
