Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-09, with the labels that each got.

#137 Refactoring
  src/components/atoms/AddListItemButton.tsx
  src/components/atoms/ElemCenteringFlexDiv.tsx
  src/components/atoms/FileMenuItem.tsx
  src/components/atoms/RenderToggleByAction.tsx
  src/components/molecules/Breadcrumbs/index.tsx
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/DatabaseMenuButton.tsx
  src/components/molecules/FileMenu.tsx
  src/components/molecules/FilePreviewer/DefaultPreviewer.tsx
  src/components/molecules/FilePreviewer/ImagePreviewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/molecules/OptionSharingSelectsItem.tsx
  src/components/molecules/Sample.tsx
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseAddButton.tsx
  src/components/organisms/DatabaseConfigModal.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/DatabaseListItem.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/components/organisms/InputConfigAddModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordAddButton.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordInfoTable.tsx
  src/components/organisms/RecordList.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
Labels: size/XXL, approved, lgtm

#139 Fix auth config
  docker-entrypoint.sh
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/utils/index.ts
Labels: size/M, approved, lgtm

#141 Fix bug that query parameter and pagination state are not sync
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
Labels: approved, size/XS

#143 Add test to CI
  .editorconfig
  .github/workflows/build_and_test.yml
  .loki/reference/chrome_laptop_DatabaseDeleteModal_Default.png
  .lokirc-ci.json
  Dockerfile
Labels: size/M, approved

#144 Fix params on accessing api file provider
  .loki/reference/chrome_laptop_DatabaseDeleteModal_Default.png
  package-lock.json
  package.json
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
  src/utils/fetchClients.tsx
Labels: size/XXL, approved, lgtm

#140 Fix bug that page is not initialized when paginate state is changed
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
Labels: approved, size/XS

#142 Improve UX for configuring database
  .loki/reference/chrome_laptop_DatabaseConfigModal_DisplayFieldsConfigBody_Presentation.png
  .loki/reference/chrome_laptop_DatabaseConfigModal_InputFieldsConfigBody_Presentation.png
  .loki/reference/chrome_laptop_DatabaseConfigModal_SearchFieldsConfigBody_Presentation.png
  .loki/reference/chrome_laptop_DatabaseConfigModal_SecretFieldsConfigBody_Presentation.png
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseConfigModal.stories.tsx
  src/components/organisms/DatabaseConfigModal.tsx
  src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/index.stories.tsx
  src/components/organisms/DatabaseConfigModal/index.tsx
  src/components/organisms/DisplayConfigEditModal.stories.tsx
  src/components/organisms/InputConfigEditModal.stories.tsx
  src/components/organisms/SearchConfigEditModal.stories.tsx
  src/components/pages/RecordsPage.tsx
Labels: size/XXL, approved

#148 Add workflow to automate merging PR created by dependabot
  .github/workflows/auto-merge.yml
  .github/workflows/build_and_deploy.yml
  .github/workflows/build_and_test.yml
  Dockerfile
Labels: size/M, approved, lgtm

#147 Test codeql-analysis
  .github/workflows/codeql-analysis.yml
Labels: size/M, approved
