Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-11, with the labels that each got.

#189 Support showing record list as marker on map
  package-lock.json
  package.json
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/RecordListMapView.stories.tsx
  src/components/organisms/RecordListMapView.tsx
  src/components/pages/RecordsPage.tsx
Labels: approved, size/L, lgtm

#190 Fix bugs that pagination parameter remain when moving between databases
  src/components/pages/RecordsPage.tsx
Labels: size/S, approved, lgtm

#206 Use new api client
  .github/workflows/build_and_test.yml
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/molecules/FilePreviewer/SourceCodePreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DatabaseListItem.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordInfoTable.tsx
  src/components/organisms/RecordList.tsx
  src/utils/fetchClients.tsx
  src/utils/index.ts
  src/utils/utilTypes.ts
Labels: approved, size/XL, lgtm

#216 Support previewing rosbag files without rosbridge
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
Labels: approved, size/L

#218 Collapse raw json view
  src/components/organisms/RecordInfo.tsx
Labels: approved, size/XS, lgtm

#211 Fix to add new clumn to last of input config
  src/components/organisms/InputConfigList.tsx
Labels: size/S, approved, lgtm

#217 Replace build tool from next.js to vite
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierignore
  .stylelintignore
  .stylelintrc.js
  Dockerfile
  README.md
  docker-compose.yaml
  docker-entrypoint.sh
  index.html
  lint-staged.config.js
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  public/manifest.json
  public/vercel.svg
  serve.json
  src/App.tsx
  src/Router.tsx
  src/components/molecules/Breadcrumbs/index.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordInfoTable.tsx
  src/main.tsx
  src/pages/DatabasesPage.tsx
  src/pages/IndexPage.tsx
  src/pages/RecordsPage.tsx
  src/pages/SamplePage.tsx
  src/pages/[[...app]].tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/healthz.ts
  src/scrollbar.global.css
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: size/XXL, approved, lgtm
