Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-07, with the labels that each got.

#66 Use GitHub-hosted runners
  .github/workflows/build_and_deploy.yml
  .github/workflows/build_and_test.yml
Labels: approved, size/XS

#65 Fix README
  README.md
Labels: approved, lgtm, size/S

#61 Refactoring
  src/components/atoms/AddListItemButton.tsx
  src/components/atoms/RenderToggleByAction.tsx
  src/components/molecules/DatabaseMenu.stories.tsx
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/DatabaseMenuButton.tsx
  src/components/molecules/FileMenu.tsx
  src/components/molecules/InputConfigListItem.stories.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/molecules/Sample.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseAddButton.tsx
  src/components/organisms/DatabaseAddModal.tsx
  src/components/organisms/DatabaseList.stories.tsx
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileDownloadUrlInjector.tsx
  src/components/organisms/FileList.stories.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/InputConfigAddModal.stories.tsx
  src/components/organisms/InputConfigAddModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/InputConfigList.stories.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/MetadataEditModal.stories.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordAddButton.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordInfo.stories.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordList.stories.tsx
  src/components/organisms/RecordList.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
  src/globalStates.ts
  src/utils/fetchClients.tsx
  src/utils/index.ts
  src/utils/utilTypes.ts
Labels: approved, lgtm, size/XXL

#72 Fix bug that error remain in modal some times
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/InputConfigAddModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordList.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
Labels: approved, size/M

#71 Show config modal after creating database
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
Labels: approved, lgtm, size/M

#67 Support changing order of input/display fields by drag and drop
  package-lock.json
  package.json
  src/components/atoms/AddListItemButton.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/InputConfigList.stories.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordEditModal.tsx
  src/utils/index.ts
  src/utils/utilTypes.ts
Labels: approved, lgtm, size/L

#73 Support editing file metadata
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/utils/fetchClients.tsx
  src/utils/index.ts
  src/utils/utilTypes.ts
Labels: approved, lgtm, size/L

#77 Show easy understood error
  src/components/organisms/DatabaseAddModal.tsx
  src/components/organisms/DisplayConfigEditModal.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/InputConfigEditModal.tsx
  src/components/organisms/RecordEditModal.tsx
  src/components/organisms/RecordList.tsx
  src/components/organisms/SearchConfigEditModal.tsx
  src/components/organisms/SecretConfigEditModal.tsx
  src/components/pages/RecordsPage.tsx
  src/utils/index.ts
Labels: approved, kind/feature, lgtm, size/M

#78 Fix appearance of browser tab
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: approved, kind/bug, lgtm, size/XS

#79 Replace built-in confirming function to ours
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/RecordDetailModal.tsx
Labels: approved, lgtm, size/M

#80 Change more icon to MoreHoriz
  src/components/molecules/DatabaseMenuButton.tsx
Labels: approved, lgtm, size/XS

#82 Fix duplicated atom key
  src/globalStates.ts
Labels: approved, lgtm, size/XS

#83 Add margin to add database modal
  src/components/organisms/DatabaseAddModal.tsx
Labels: approved, lgtm, size/L

#81 Improve breadcrumbs
  src/components/molecules/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/molecules/Breadcrumbs/index.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
Labels: approved, lgtm, size/L

#85 Delete unused component
  src/components/molecules/DisplayConfigListItem.stories.tsx
  src/components/molecules/DisplayConfigListItem.tsx
  src/components/molecules/SearchConfigListItem.tsx
  src/components/organisms/DisplayConfigList.stories.tsx
  src/components/organisms/DisplayConfigList.tsx
  src/components/organisms/SearchConfigList.tsx
Labels: approved, lgtm, size/L

#88 Support previewing rosbag file
  src/components/molecules/FilePreviewer/DefaultPreviewer.stories.tsx
  src/components/molecules/FilePreviewer/DefaultPreviewer.tsx
  src/components/molecules/FilePreviewer/FilePreviewer.stories.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/RosbagPreviewer.stories.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.stories.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.tsx
  src/components/molecules/FilePreviewer/VideoPreviewer.stories.tsx
  src/components/molecules/FilePreviewer/VideoPreviewer.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/molecules/FilePreviewer/types.ts
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/utils/fetchClients.tsx
Labels: approved, lgtm, size/XL

#87 Make scrollablity of database list clear
  package-lock.json
  package.json
  src/components/organisms/DatabaseList.tsx
Labels: approved, lgtm, size/M

#90 Add system metadata to created file
  src/components/organisms/DatabaseAddModal.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/utils/index.ts
Labels: approved, lgtm, size/L

#76 Support changing database information
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseAddButton.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/pages/RecordsPage.tsx
  src/utils/fetchClients.tsx
Labels: approved, lgtm, size/L

#84 Add story
  src/components/atoms/AddListItemButton.stories.tsx
  src/components/atoms/RenderToggleByAction.stories.tsx
  src/components/molecules/SoloSelect.stories.tsx
  src/components/organisms/ControlledDatabaseMenuButton.stories.tsx
  src/components/organisms/DatabaseAddButton.stories.tsx
  src/components/organisms/DatabaseAddModal.stories.tsx
  src/components/organisms/DisplayConfigEditModal.stories.tsx
  src/components/organisms/ExportMetadataModal.stories.tsx
  src/components/organisms/InputConfigEditModal.stories.tsx
  src/components/organisms/MetadataInputFieldList.stories.tsx
  src/components/organisms/RecordAddButton.stories.tsx
  src/components/organisms/SearchConfigEditModal.stories.tsx
  src/components/organisms/SecretConfigEditModal.stories.tsx
Labels: approved, lgtm, size/L

#91 Fix bug of modal form cut out
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/OptionSharingSelects.tsx
Labels: approved, lgtm, size/XS

#92 Fix build bug
  src/components/organisms/DatabaseAddModal.stories.tsx
Labels: approved, size/S

#95 Replace Table of dataware-tools to DataGrid of material-ui
  package-lock.json
  package.json
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/RecordList.tsx
Labels: approved, lgtm, size/L

#101 Support deletting database
  src/components/organisms/DatabaseList.tsx
Labels: approved, lgtm, size/L

#102 Bump app-common
  package-lock.json
  package.json
Labels: approved, size/XS

#105 Bump dependencies
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
Labels: approved, lgtm, size/L

#111 Support sorting record list
  package-lock.json
  src/components/organisms/RecordList.tsx
  src/components/pages/RecordsPage.tsx
  src/globalStates.ts
Labels: approved, lgtm, size/M

#114 Fix bug that duplicated file error does not occur
  src/components/organisms/RecordDetailModal.tsx
  src/utils/fetchClients.tsx
Labels: approved, lgtm, size/XS
