Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-12, with the labels that each got.

#228 Bump storybook
  .eslintrc.js
  package-lock.json
  package.json
  src/test-utils.tsx
Labels: size/XXL, approved, lgtm

#223 Support configuring column data type
  src/components/molecules/InputConfigListItem.stories.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.tsx
  src/components/organisms/FileEditModal.tsx
  src/components/organisms/InputConfigList.stories.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/InputConfigListItemModal.stories.tsx
  src/components/organisms/InputConfigListItemModal.tsx
  src/components/organisms/MetadataEditModal.stories.tsx
  src/components/organisms/MetadataInputFieldList.stories.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/RecordEditModal.tsx
  src/utils/index.ts
  src/utils/utilTypes.ts
Labels: approved, size/L, lgtm

#250 Support for job-type `ros-provider-with-pydtk`
  package-lock.json
  package.json
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/components/molecules/FilePreviewer/index.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FilePreviewModal.tsx
Labels: size/M, approved, lgtm

#254 Support for api-job-store with database-id
  package.json
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/index.tsx
  src/utils/fetchClients.tsx
  src/utils/utilTypes.ts
Labels: approved, size/L, lgtm

#257 Bump mui
  package-lock.json
  package.json
Labels: approved, size/L, lgtm

#258 Fix "Dependabot can't authenticate to a private package registry" error
  .github/dependabot.yml
Labels: approved, size/XS

#259 Bug fix on dependabot config
  .github/dependabot.yml
Labels: approved, size/XS

#266 Uninstall rollup-plugin
  package-lock.json
  package.json
Labels: approved, size/L, lgtm

#278 Fix build config for symlinking app common
  .storybook/main.js
  tsconfig.json
  vite.config.ts
Labels: size/S, approved, lgtm

#290 Bump app-common to 21.12.10
  package.json
Labels: approved, size/XS, lgtm

#296 Run auto formatting of prettier
  src/components/molecules/FilePreviewer/CsvPreviewer.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.stories.tsx
  src/components/molecules/FilePreviewer/VideoPreviewer.stories.tsx
  src/components/molecules/OptionSharingSelectsItem.tsx
  src/components/organisms/ControlledDatabaseMenuButton.tsx
  src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/index.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FilePreviewModal.stories.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/RecordList.tsx
Labels: approved, size/L, lgtm

#305 Bump app-common
  package-lock.json
  package.json
Labels: size/S, approved, lgtm
