Repository dataware-tools/app-data-browser-next, pull requests merged in 2021-10, with the labels that each got.

#157 Bump MUI
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/atoms/AddListItemButton.tsx
  src/components/atoms/ElemCenteringFlexDiv.tsx
  src/components/atoms/FileMenuItem.stories.tsx
  src/components/atoms/FileMenuItem.tsx
  src/components/molecules/Breadcrumbs/Breadcrumbs.stories.tsx
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/molecules/Breadcrumbs/index.tsx
  src/components/molecules/DatabaseMenu.tsx
  src/components/molecules/DatabaseMenuButton.tsx
  src/components/molecules/FileMenu.tsx
  src/components/molecules/FilePreviewer/AudioPreviewer.tsx
  src/components/molecules/FilePreviewer/CsvPreviewer.tsx
  src/components/molecules/FilePreviewer/ImagePreviewer.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobSubmitter.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobTemplateInfo.tsx
  src/components/molecules/FilePreviewer/RosbagPreviewer/JobViewer.tsx
  src/components/molecules/FilePreviewer/TextPreviewer.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/molecules/OptionSharingSelectsItem.tsx
  src/components/molecules/Sample.tsx
  src/components/molecules/SoloSelect.tsx
  src/components/organisms/DatabaseAddButton.tsx
  src/components/organisms/DatabaseConfigModal/DisplayFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SearchFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/SecretFieldsConfigBody.tsx
  src/components/organisms/DatabaseConfigModal/index.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/DatabaseList.tsx
  src/components/organisms/DatabaseListItem.stories.tsx
  src/components/organisms/DatabaseListItem.tsx
  src/components/organisms/ExportMetadataModal.tsx
  src/components/organisms/FileList.tsx
  src/components/organisms/FileListItem.stories.tsx
  src/components/organisms/FileListItem.tsx
  src/components/organisms/FilePreviewModal.tsx
  src/components/organisms/InputConfigAddModal.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.tsx
  src/components/organisms/OptionSharingSelects.tsx
  src/components/organisms/RecordAddButton.tsx
  src/components/organisms/RecordDetailModal.tsx
  src/components/organisms/RecordInfo.tsx
  src/components/organisms/RecordInfoTable.tsx
  src/components/organisms/RecordList.tsx
  src/components/pages/DatabasesPage.tsx
  src/components/pages/RecordsPage.tsx
  src/components/pages/SamplePage.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/test-utils.tsx
Labels: approved, size/XL, lgtm

#167 Bump node
  .npmrc
  Dockerfile
  package-lock.json
  package.json
Labels: size/XXL, approved, lgtm

#172 Bump swr
  package-lock.json
  package.json
  src/setupTest.ts
Labels: size/S, approved, lgtm

#173 Make input-columns configurable
  .loki/reference/chrome_laptop_DatabaseConfigModal_InputFieldsConfigBody_Presentation.png
  .loki/reference/chrome_laptop_InputConfigListItem_Default.png
  .loki/reference/chrome_laptop_InputConfigList_Default.png
  src/components/molecules/InputConfigListItem.stories.tsx
  src/components/molecules/InputConfigListItem.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.stories.tsx
  src/components/organisms/DatabaseConfigModal/InputFieldsConfigBody.tsx
  src/components/organisms/InputConfigAddModal.stories.tsx
  src/components/organisms/InputConfigList.stories.tsx
  src/components/organisms/InputConfigList.tsx
  src/components/organisms/InputConfigListItemModal.stories.tsx
  src/components/organisms/InputConfigListItemModal.tsx
Labels: approved, size/L, lgtm
