Repository dataware-tools/app-data-browser-next, pull requests merged in 2022-01, with the labels that each got.

#330 Add link to document on DefaultPreviewer
  .loki/reference/chrome_laptop_FilePreview_DefaultPreviewer_Default.png
  src/components/molecules/FilePreviewer/DefaultPreviewer.tsx
Labels: size/S, approved

#312 Fix usage of swr
  src/components/molecules/Sample.tsx
  src/utils/index.ts
Labels: approved, size/XS, lgtm

#331 Fix the way of validating number
  .loki/reference/chrome_laptop_MetadataInputFieldList_Default.png
  src/components/organisms/MetadataEditModal.tsx
  src/components/organisms/MetadataInputFieldList.stories.tsx
  src/components/organisms/MetadataInputFieldList.tsx
Labels: approved, size/L, lgtm

#311 Bump react-router-dom
  .storybook/preview.js
  package-lock.json
  package.json
  src/Router.tsx
  src/components/molecules/Breadcrumbs/BreadcrumbsItem.tsx
  src/components/organisms/DatabaseDeleteModal.tsx
  src/components/organisms/DatabaseList.tsx
  src/pages/DatabasesPage.tsx
  src/pages/IndexPage.tsx
  src/pages/RecordsPage.tsx
Labels: approved, size/L, lgtm

#347 Fix bug that Number and Datetime can't be changed to empty
  src/components/organisms/MetadataEditModal.tsx
Labels: approved, size/XS, lgtm

#348 Confirm trashing changed data
  package-lock.json
  package.json
  src/components/organisms/DatabaseConfigModal/index.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/MetadataEditModal.tsx
Labels: approved, size/L, lgtm

#329 Fix bugs that "copy to clip board" not works
  src/components/organisms/RecordInfo.tsx
Labels: approved, size/XS, lgtm

#354 Show deleted target name
  src/components/organisms/FileList.tsx
  src/components/organisms/RecordList.tsx
Labels: approved, size/XS, lgtm

#365 Show menu button even if database have error
  src/pages/RecordsPage.tsx
Labels: size/M, approved, lgtm

#366 Confirm closing window when changed data exists
  package-lock.json
  package.json
  src/components/organisms/DatabaseConfigModal/index.tsx
  src/components/organisms/DatabaseEditModal.tsx
  src/components/organisms/MetadataEditModal.tsx
Labels: size/M, approved, lgtm

#372 Fix the feature of downloading metadata
  src/components/organisms/ExportMetadataModal.tsx
Labels: size/M, approved, lgtm
